services:
  cdc-mysql:
    image: bitnami/mysql:8.0
    container_name: cdc-mysql
    hostname: cdc-mysql
    restart: on-failure:3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=dbeaver
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=cdc
    volumes:
      - mysql-data:/bitnami/mysql/data
      - ./resources:/docker-entrypoint-initdb.d
    networks:
      - cdc-network

  cdc-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: cdc-elasticsearch
    hostname: cdc-elasticsearch
    restart: on-failure:3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - cdc-network

  cdc-kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: cdc-kibana
    hostname: cdc-kibana
    restart: on-failure:3
    depends_on:
      - cdc-elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://cdc-elasticsearch:9200
    networks:
      - cdc-network

  cdc-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.5
    container_name: cdc-zookeeper
    hostname: cdc-zookeeper
    restart: on-failure:3
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - cdc-network

  cdc-kafka:
    image: confluentinc/cp-kafka:7.6.5
    container_name: cdc-kafka
    hostname: cdc-kafka
    restart: on-failure:3
    depends_on:
      - cdc-zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=cdc-zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://cdc-kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - cdc-network

  cdc-kafka-connect:
    image: confluentinc/cp-kafka-connect:7.6.5
    container_name: cdc-kafka-connect
    hostname: cdc-kafka-connect
    restart: on-failure:3
    depends_on:
      - cdc-kafka
      - cdc-mysql
      - cdc-elasticsearch
    ports:
      - "8083:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=cdc-kafka:9093
      - CONNECT_GROUP_ID=kafka-connect-group
      - CONNECT_REST_PORT=8083
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_CONFIG_STORAGE_TOPIC=docker-connect-configs
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_TOPIC=docker-connect-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_TOPIC=docker-connect-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false 
      - CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components
    command: >
      bash -c "confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest &&
      confluent-hub install --no-prompt debezium/debezium-connector-mysql:latest &&
      /etc/confluent/docker/run"
    volumes:
      - kafka-connect-data:/var/lib/kafka-connect
    networks:
      - cdc-network

networks:
  cdc-network:
    name: cdc-network
    driver: bridge

volumes:
  mysql-data:
  elasticsearch-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  kafka-connect-data:
