services:
  cdc-mysql:
    image: bitnami/mysql:8.4
    container_name: cdc-mysql
    hostname: cdc-mysql
    restart: on-failure:3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=dbeaver
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=change_data_capture
    volumes:
      - cdc-mysql-data:/bitnami/mysql/data
      - ./resources:/docker-entrypoint-initdb.d
    networks:
      - cdc-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s

  cdc-kafka:
    image: bitnami/kafka:3.9
    container_name: cdc-kafka
    hostname: cdc-kafka
    restart: on-failure:3
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9092,INTERNAL://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://cdc-kafka:9093,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@cdc-kafka:9092
    volumes:
      - cdc-kafka-data:/bitnami/kafka
    networks:
      - cdc-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "cdc-kafka:9093", "--list"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s

  cdc-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: cdc-kafka-ui
    hostname: cdc-kafka-ui
    restart: on-failure:3
    depends_on:
      - cdc-kafka
    ports:
      - "9090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=cdc-kafka:9093
    networks:
      - cdc-network

  cdc-debezium-connect:
    image: debezium/connect:3.0.0.Final
    container_name: cdc-debezium-connect
    hostname: cdc-debezium-connect
    restart: on-failure:3
    depends_on:
      - cdc-mysql
      - cdc-kafka
      - cdc-kafka-ui
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=cdc-kafka:9093
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_SCRIPTING=true
    networks:
      - cdc-network

  cdc-sink-connect:
    image: confluentinc/cp-kafka-connect:7.9.0
    container_name: cdc-sink-connect
    hostname: cdc-sink-connect
    restart: on-failure:3
    depends_on:
      - cdc-kafka
      - cdc-kafka-ui
    ports:
      - "8084:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=cdc-kafka:9093
      - CONNECT_GROUP_ID=2
      - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs
      - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets
      - CONNECT_STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_REST_PORT=8084
      - CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars
    networks:
      - cdc-network

networks:
  cdc-network:
    name: cdc-network
    driver: bridge

volumes:
  cdc-mysql-data:
    name: cdc-mysql-data
    driver: local
  cdc-kafka-data:
    name: cdc-kafka-data
    driver: local
